#!/bin/sh

# Create Developer App
# https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps

curl \
  -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/xml" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/developers/$APIGEE_DEVELOPER/apps" \
  -d @$APIGEE_APP
