#!/bin/sh

# Create KVM Entry
# https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/keyvaluemaps/%7Bmap_name%7D/entries 

curl \
  -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/keyvaluemaps/$APIGEE_KVM/entries" \
  -d '{"name": "$APIGEE_KEY", "value": "$APIGEE_VALUE"}'
