#!/bin/sh

# Delete Cache
# https://apidocs.apigee.com/management/apis/delete/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/caches/%7Bcache_name%7D 

curl \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/caches/$APIGEE_CACHE"

